const data = {
  products: [
    {
      name: "Monster Quarterback Legend Jersey",
      slug: "monster-quarterback-legend-jersey",
      category: "NFL Monster Collection",
      description: "Fearsome quarterback monster ready to lead your team to victory",
      images: ["/images/NFL/1.jpg"],
      price: 129.99,
      brand: "Monster NFL",
      rating: 4.8,
      numReviews: 15,
      stock: 10,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Beast Mode Running Back Jersey",
      slug: "beast-mode-running-back-jersey",
      category: "NFL Monster Collection",
      description: "Unstoppable monster running back that breaks through any defense",
      images: ["/images/NFL/2.jpg"],
      price: 119.99,
      brand: "Monster NFL",
      rating: 4.7,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Monster Defense Tackle Jersey",
      slug: "monster-defense-tackle-jersey",
      category: "NFL Monster Collection",
      description: "Defensive monster that dominates the line of scrimmage",
      images: ["/images/NFL/3.jpg"],
      price: 109.99,
      brand: "Monster NFL",
      rating: 4.6,
      numReviews: 10,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Creature Wide Receiver Jersey",
      slug: "creature-wide-receiver-jersey",
      category: "NFL Monster Collection",
      description: "Lightning-fast monster receiver with supernatural catching abilities",
      images: ["/images/NFL/4.jpg"],
      price: 124.99,
      brand: "Monster NFL",
      rating: 4.9,
      numReviews: 18,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Monster Safety Guardian Jersey",
      slug: "monster-safety-guardian-jersey",
      category: "NFL Monster Collection",
      description: "Elite monster safety that patrols the defensive backfield",
      images: ["/images/NFL/5.jpg"],
      price: 114.99,
      brand: "Monster NFL",
      rating: 4.5,
      numReviews: 14,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Behemoth Linebacker Jersey",
      slug: "behemoth-linebacker-jersey",
      category: "NFL Monster Collection",
      description: "Monstrous linebacker that strikes fear into opposing offenses",
      images: ["/images/NFL/6.jpg"],
      price: 119.99,
      brand: "Monster NFL",
      rating: 4.7,
      numReviews: 16,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Tight End Jersey",
      slug: "monster-tight-end-jersey",
      category: "NFL Monster Collection",
      description: "Versatile monster tight end that dominates in both blocking and receiving",
      images: ["/images/NFL/7.jpg"],
      price: 117.99,
      brand: "Monster NFL",
      rating: 4.6,
      numReviews: 11,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Creature Kicker Jersey",
      slug: "creature-kicker-jersey",
      category: "NFL Monster Collection",
      description: "Precision monster kicker with supernatural leg power",
      images: ["/images/NFL/8.jpeg"],
      price: 99.99,
      brand: "Monster NFL",
      rating: 4.4,
      numReviews: 9,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Punter Jersey",
      slug: "monster-punter-jersey",
      category: "NFL Monster Collection",
      description: "Monster punter with incredible field position control",
      images: ["/images/NFL/9.jpeg"],
      price: 99.99,
      brand: "Monster NFL",
      rating: 4.3,
      numReviews: 8,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Pitcher Legend Jersey",
      slug: "monster-pitcher-legend-jersey",
      category: "MLB Monster Collection",
      description: "Legendary monster pitcher with supernatural throwing abilities",
      images: ["/images/MLB/1.jpg"],
      price: 119.99,
      brand: "Monster MLB",
      rating: 4.8,
      numReviews: 14,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Beast Mode Slugger Jersey",
      slug: "beast-mode-slugger-jersey",
      category: "MLB Monster Collection",
      description: "Power-hitting monster with incredible home run strength",
      images: ["/images/MLB/2.jpg"],
      price: 124.99,
      brand: "Monster MLB",
      rating: 4.9,
      numReviews: 16,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Monster Shortstop Elite Jersey",
      slug: "monster-shortstop-elite-jersey",
      category: "MLB Monster Collection",
      description: "Agile monster shortstop with supernatural fielding skills",
      images: ["/images/MLB/3.jpg"],
      price: 114.99,
      brand: "Monster MLB",
      rating: 4.7,
      numReviews: 12,
      stock: 15,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Creature Outfielder Jersey",
      slug: "creature-outfielder-jersey",
      category: "MLB Monster Collection",
      description: "Swift monster outfielder that covers the field with supernatural speed",
      images: ["/images/MLB/4.jpg"],
      price: 109.99,
      brand: "Monster MLB",
      rating: 4.6,
      numReviews: 10,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Catcher Guardian Jersey",
      slug: "monster-catcher-guardian-jersey",
      category: "MLB Monster Collection",
      description: "Defensive monster catcher with incredible game-calling abilities",
      images: ["/images/MLB/5.jpg"],
      price: 119.99,
      brand: "Monster MLB",
      rating: 4.8,
      numReviews: 13,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Striker Legend Jersey",
      slug: "monster-striker-legend-jersey",
      category: "Soccer Monster Collection",
      description: "Elite monster striker with supernatural goal-scoring abilities",
      images: ["/images/Soccer/1.jpg"],
      price: 119.99,
      brand: "Monster Soccer",
      rating: 4.9,
      numReviews: 20,
      stock: 15,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Beast Mode Goalkeeper Jersey",
      slug: "beast-mode-goalkeeper-jersey",
      category: "Soccer Monster Collection",
      description: "Unstoppable monster goalkeeper with incredible shot-stopping powers",
      images: ["/images/Soccer/2.jpg"],
      price: 124.99,
      brand: "Monster Soccer",
      rating: 4.8,
      numReviews: 16,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Monster Midfielder Maestro Jersey",
      slug: "monster-midfielder-maestro-jersey",
      category: "Soccer Monster Collection",
      description: "Creative monster midfielder with supernatural playmaking vision",
      images: ["/images/Soccer/3.jpg"],
      price: 114.99,
      brand: "Monster Soccer",
      rating: 4.7,
      numReviews: 14,
      stock: 10,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Creature Defender Elite Jersey",
      slug: "creature-defender-elite-jersey",
      category: "Soccer Monster Collection",
      description: "Dominant monster defender that commands the backline",
      images: ["/images/Soccer/4.jpg"],
      price: 109.99,
      brand: "Monster Soccer",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Winger Speed Jersey",
      slug: "monster-winger-speed-jersey",
      category: "Soccer Monster Collection",
      description: "Lightning-fast monster winger with supernatural dribbling skills",
      images: ["/images/Soccer/5.jpg"],
      price: 119.99,
      brand: "Monster Soccer",
      rating: 4.8,
      numReviews: 15,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default data;
