import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "John Doe",
      email: "user@example.com",
      password: hashSync("123456", 10),
    },
    {
      name: "Admin",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "ADMIN",
    },
  ],
  products: [
    {
      name: "Monster Quarterback Legend Jersey",
      slug: "monster-quarterback-legend-jersey",
      category: "NFL Monster Collection",
      description: "Fearsome quarterback monster ready to lead your team to victory",
      images: ["/images/sample-products/1.jpg"],
      price: 129.99,
      brand: "Monster NFL",
      rating: 4.8,
      numReviews: 15,
      stock: 10,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Beast Mode Running Back Jersey",
      slug: "beast-mode-running-back-jersey",
      category: "NFL Monster Collection",
      description: "Unstoppable monster running back that breaks through any defense",
      images: ["/images/sample-products/2.jpg"],
      price: 119.99,
      brand: "Monster NFL",
      rating: 4.7,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Monster Defense Tackle Jersey",
      slug: "monster-defense-tackle-jersey",
      category: "NFL Monster Collection",
      description: "Defensive monster that dominates the line of scrimmage",
      images: ["/images/sample-products/3.jpg"],
      price: 109.99,
      brand: "Monster NFL",
      rating: 4.6,
      numReviews: 10,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Creature Wide Receiver Jersey",
      slug: "creature-wide-receiver-jersey",
      category: "NFL Monster Collection",
      description: "Lightning-fast monster receiver with supernatural catching abilities",
      images: ["/images/sample-products/4.jpg"],
      price: 124.99,
      brand: "Monster NFL",
      rating: 4.9,
      numReviews: 18,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Monster Safety Guardian Jersey",
      slug: "monster-safety-guardian-jersey",
      category: "NFL Monster Collection",
      description: "Elite monster safety that patrols the defensive backfield",
      images: ["/images/sample-products/5.jpg"],
      price: 114.99,
      brand: "Monster NFL",
      rating: 4.5,
      numReviews: 14,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Behemoth Linebacker Jersey",
      slug: "behemoth-linebacker-jersey",
      category: "NFL Monster Collection",
      description: "Monstrous linebacker that strikes fear into opposing offenses",
      images: ["/images/sample-products/6.jpg"],
      price: 119.99,
      brand: "Monster NFL",
      rating: 4.7,
      numReviews: 16,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Tight End Jersey",
      slug: "monster-tight-end-jersey",
      category: "NFL Monster Collection",
      description: "Versatile monster tight end that dominates in both blocking and receiving",
      images: ["/images/sample-products/7.jpg"],
      price: 117.99,
      brand: "Monster NFL",
      rating: 4.6,
      numReviews: 11,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Creature Kicker Jersey",
      slug: "creature-kicker-jersey",
      category: "NFL Monster Collection",
      description: "Precision monster kicker with supernatural leg power",
      images: ["/images/sample-products/8.jpeg"],
      price: 99.99,
      brand: "Monster NFL",
      rating: 4.4,
      numReviews: 9,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Monster Punter Jersey",
      slug: "monster-punter-jersey",
      category: "NFL Monster Collection",
      description: "Monster punter with incredible field position control",
      images: ["/images/sample-products/9.jpeg"],
      price: 99.99,
      brand: "Monster NFL",
      rating: 4.3,
      numReviews: 8,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
